# Generated by Django 4.2.2 on 2023-06-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='dance',
            field=models.CharField(default='dance.mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='mask',
            field=models.CharField(default='masks.mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='novel',
            field=models.CharField(default='novel.mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='pose',
            field=models.CharField(default='pose.mp4', max_length=100),
        ),
    ]
