# Generated by Django 4.2.2 on 2023-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0003_rename_image_post_file_post_dance_post_mask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='dance',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='mask',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='novel',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='pose',
            field=models.CharField(default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
