# Generated by Django 4.2.2 on 2023-06-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0004_remove_post_id_alter_post_dance_alter_post_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='mask_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='novel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pose_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
