# Generated by Django 4.2.2 on 2023-06-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0005_post_created_at_post_dance_time_post_mask_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dance_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mask_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='novel_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pose_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
