# Generated by Django 4.2.2 on 2023-06-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0006_alter_post_dance_time_alter_post_mask_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='train_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
