# Generated by Django 4.2.2 on 2023-06-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0007_post_train_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='train_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
