# Generated by Django 4.2.2 on 2023-06-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerf', '0008_alter_post_train_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metrics',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
